/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with email and password.
         * @description On success: 200 with access + refresh token pair and the user payload.
         *     On any failure: 401 with the standard error envelope. NO enumeration —
         *     "user not found" and "wrong password" are indistinguishable on the wire.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token for a fresh access + refresh pair.
         * @description Industry-standard refresh-token ROTATION with REPLAY DETECTION.
         *     See services/auth_service.refresh_session for the full state machine.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the presented refresh token.
         * @description Idempotent. A missing or already-consumed token returns 200 — the
         *     frontend just clears its local storage. The access token is NOT
         *     revoked; it expires naturally within ACCESS_TOKEN_EXPIRE_MINUTES.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume an invite token and create the User row.
         * @description Used by the invitee who clicked the invite URL. On success, the User
         *     row is created AND they are auto-logged-in (returned token pair).
         *     On any invite failure, generic 400 — invalid/expired/consumed are
         *     indistinguishable to the wire.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current authenticated user.
         * @description Used by the frontend on app boot to hydrate its auth context.
         *     Resolves identity STRICTLY from the JWT (via get_current_user) +
         *     one DB read for freshness. No tokens here — frontend already has them.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users with optional filters. */
        get: operations["list_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single user detail. */
        get: operations["get_user_admin_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Partial update of a user (full_name and/or role). */
        patch: operations["patch_user_admin_users__user_id__patch"];
        trace?: never;
    };
    "/admin/users/{user_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a user (sets is_active=true). */
        post: operations["activate_user_admin_users__user_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a user. Revokes all their refresh tokens. */
        post: operations["deactivate_user_admin_users__user_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invitations with optional status filter. */
        get: operations["list_invitations_admin_invitations_get"];
        put?: never;
        /** Issue a new invitation. Plaintext token is returned exactly once. */
        post: operations["create_invitation_admin_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/invitations/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a pending invitation. Idempotent. */
        delete: operations["revoke_invitation_admin_invitations__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs/action-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enumerate vocabularies for the admin filter dropdowns.
         * @description Returns the FULL controlled vocabulary, not just the values currently
         *     observed in audit_logs. The frontend's filter dropdown should let
         *     admins query for action types that haven't happened yet (e.g.,
         *     'show me TOKEN_REPLAY_DETECTED rows' on a fresh deploy with zero
         *     such rows). Sourced from services.audit_vocab.
         */
        get: operations["get_audit_vocabularies_admin_audit_logs_action_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cursor-paginated audit log with optional filters. */
        get: operations["list_audit_logs_admin_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single audit row detail (full extra_metadata). */
        get: operations["get_audit_log_admin_audit_logs__log_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/system/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** High-level platform health for the admin dashboard. */
        get: operations["system_overview_admin_system_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/system/pipeline-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightweight pipeline status (Admin or Analyst). */
        get: operations["pipeline_status_admin_system_pipeline_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all global settings. */
        get: operations["list_settings_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a single setting by key. */
        get: operations["get_setting_admin_settings__key__get"];
        /** Update a setting. Per-key validation enforced. */
        put: operations["update_setting_admin_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthcheck
         * @description Confirms that the API process is running.
         */
        get: operations["healthcheck_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database Healthcheck
         * @description Confirms that the API can still reach the configured database.
         */
        get: operations["database_healthcheck_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Registry
         * @description Page 2: Populates the model selection dropdown.
         */
        get: operations["get_model_registry_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard-stats/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description Page 1: Returns the fast snapshot metrics for the dashboard.
         *
         *     ISO 25010 — Reliability → Fault Tolerance:
         *       Uses hasattr/getattr guards so that pre-migration model rows
         *       (which lack KPI columns in the DB) return a structured 404
         *       instead of an unhandled AttributeError that leaks a 500 trace.
         *
         *     ISO 25010 — Maintainability → Analysability:
         *       The 'schema_incomplete' detail string tells ops exactly which
         *       model row is broken and why, without exposing internal tracebacks.
         */
        get: operations["get_dashboard_stats_api_dashboard_stats__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Business Analytics
         * @description Tab 1: Business Analytics — year-aware via ?year= query parameter.
         *
         *     Behavior:
         *       - year=None or year="overall" → returns the full-dataset aggregation.
         *       - year="2023"                 → returns the 2023-scoped slice.
         *       - year="9999" (invalid)       → returns 400 with sanitized error.
         *       - model_id provided           → scopes snapshot to that model's training data.
         *       - model_id omitted            → uses the most recent snapshot.
         *
         *     ISO 25010:
         *       Performance Efficiency → Time Behavior:
         *         Single SELECT on dataset_snapshots. No aggregation on the request path.
         *         The ?year= filter is a dict lookup on a pre-computed JSON blob — O(1).
         *       Maintainability → Modifiability:
         *         _slice_year() is the single point where year-filtering semantics live.
         *         Adding quarterly view is one new helper — zero schema changes.
         *       Reliability → Fault Tolerance:
         *         Invalid year → sanitized 400. Null JSON columns → empty list defaults.
         *         Never exposes raw Python exceptions to the frontend.
         */
        get: operations["get_business_analytics_api_business_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advanced-metrics/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Advanced Metrics
         * @description Page 2: Full statistical view for the MLOps panel.
         */
        get: operations["get_advanced_metrics_api_advanced_metrics__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast-outlook/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Forecast Outlook
         * @description Tab 2: Single endpoint serving KPI cards and Critical Forecast Weeks table.
         *     One DB query — all aggregation derived in Python from the same in-memory list.
         *
         *     ISO 25010:
         *       Performance Efficiency → Time Behavior:
         *         1 DB query replaces 2. All aggregation is O(n) over ≤16 rows.
         *       Reliability → Fault Tolerance:
         *         Null risk_flag defaults to "MEDIUM" with a debug log trace.
         *         Model existence validated before any cache query.
         */
        get: operations["get_forecast_outlook_api_forecast_outlook__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/historical-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Historical Ledger */
        get: operations["get_historical_ledger_api_historical_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Pos Data
         * @description Page 3: Safely ingests KJS CSV data and prevents duplicate dates.
         *
         *     Phase 5: now requires ADMIN or ANALYST role. Audit rows carry the
         *     real actor; the `unauthenticated: true` marker is no longer added
         *     (the actor is real and `audit_service` only adds the marker when
         *     actor is None).
         */
        post: operations["upload_pos_data_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast-graph/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast Graph */
        get: operations["get_forecast_graph_api_forecast_graph__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategic-actions/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategic Actions
         * @description Page 1: Prescriptive analytics.
         *     Derives actionable recommendations from forecast_cache data.
         *     Rule-based engine — no ML required.
         */
        get: operations["get_strategic_actions_api_strategic_actions__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Retrain
         * @description Phase 3: every retrain — successful or failed — writes an audit row.
         *     The action_type is FORECAST_RUN on success, FORECAST_FAILED otherwise.
         *     The audit row's metadata captures the request payload (which exog
         *     factors, which model selection) so a future "why was this model
         *     trained?" investigation has the inputs preserved.
         *
         *     Phase 5: requires Admin or Analyst. Every retrain — successful or failed —
         *     writes an audit row attributing the actor.
         */
        post: operations["trigger_retrain_api_retrain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename Model
         * @description Page 2: Renames a specific model in the registry.
         *
         *     Phase 3: every successful rename writes a MODEL_RENAMED audit row
         *     with both the old and the new name. The audit log preserves rename
         *     history that the SarimaxModel row itself does not — once you've
         *     renamed Model #42 from "v10.1-experimental" to "production",
         *     the column shows the new name and history is lost without the audit.
         *
         *     Phase 5 will add Depends(require_analyst); today actor=None.
         */
        patch: operations["rename_model_api_models__model_id__rename_patch"];
        trace?: never;
    };
    "/api/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Model
         * @description Phase 3: every successful deletion writes a MODEL_DELETED audit row
         *     with the model_name and key metadata captured BEFORE the delete —
         *     forensic preservation of "what was here." Cascade also wipes
         *     ModelDiagnostic and ForecastCache rows; their counts go in metadata.
         *
         *     Phase 5 will add Depends(require_admin); today actor=None.
         */
        delete: operations["delete_model_api_models__model_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUserDetailResponse
         * @description Full detail. Same shape today; reserves room for future fields.
         */
        AdminUserDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "ADMIN" | "ANALYST" | "VIEWER";
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By User Id */
            created_by_user_id?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AdminUserListItem
         * @description User row as seen in the admin table. Excludes hashed_password.
         */
        AdminUserListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "ADMIN" | "ANALYST" | "VIEWER";
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By User Id */
            created_by_user_id?: string | null;
        };
        /**
         * AdminUserListResponse
         * @description Offset-paginated list of users.
         */
        AdminUserListResponse: {
            /** Items */
            items: components["schemas"]["AdminUserListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** AdvancedCharts */
        AdvancedCharts: {
            /** Residuals */
            residuals?: components["schemas"]["ResidualPoint"][];
            /** Acf */
            acf?: components["schemas"]["CorrelationPoint"][];
            /** Pacf */
            pacf?: components["schemas"]["CorrelationPoint"][];
            /** Correlation Heatmap */
            correlation_heatmap?: components["schemas"]["CorrelationHeatmapPoint"][];
            /** Validation Graph */
            validation_graph?: components["schemas"]["ValidationPoint"][];
        };
        /** AdvancedMetricsResponse */
        AdvancedMetricsResponse: {
            model_params: components["schemas"]["ModelParams"];
            statistics: components["schemas"]["ModelStatistics"];
            statistical_tests: components["schemas"]["ModelTests"];
            charts: components["schemas"]["AdvancedCharts"];
        };
        /** AirlineCount */
        AirlineCount: {
            /** Airline Code */
            airline_code: string;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /**
         * AuditActionTypesResponse
         * @description Enumeration of every valid action_type, for the admin filter dropdown.
         */
        AuditActionTypesResponse: {
            /** Action Types */
            action_types: string[];
            /** Modules */
            modules: string[];
        };
        /** AuditLogItem */
        AuditLogItem: {
            /** Id */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** User Id */
            user_id?: string | null;
            /** User Email Snapshot */
            user_email_snapshot?: string | null;
            /** Action Type */
            action_type: string;
            /** Module */
            module: string;
            /** Target Resource */
            target_resource?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "SUCCESS" | "FAILED";
            /** Ip Address */
            ip_address?: string | null;
            /** User Agent */
            user_agent?: string | null;
            /** Extra Metadata */
            extra_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AuditLogPageResponse
         * @description Cursor-paginated page of audit rows.
         *
         *     `next_cursor` is null when there are no more rows. The frontend
         *     treats it as opaque — just round-trip it as the `?cursor=` parameter
         *     on the next request. Internally it encodes (last_timestamp, last_id).
         */
        AuditLogPageResponse: {
            /** Items */
            items: components["schemas"]["AuditLogItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * AuthenticatedUser
         * @description The user-shaped subset that's safe to return on the wire.
         *     NEVER add `hashed_password` here. Add fields by name to grow.
         */
        AuthenticatedUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "ADMIN" | "ANALYST" | "VIEWER";
            /** Is Active */
            is_active: boolean;
        };
        /** Body_upload_pos_data_api_upload_post */
        Body_upload_pos_data_api_upload_post: {
            /** File */
            file: string;
        };
        /** BookingsByMonth */
        BookingsByMonth: {
            /** Month */
            month: string;
            /** Bookings */
            bookings: number;
        };
        /** BookingsByYear */
        BookingsByYear: {
            /** Year */
            year: string;
            /** Bookings */
            bookings: number;
        };
        /** BusinessAnalyticsResponse */
        BusinessAnalyticsResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Total Transaction Count */
            total_transaction_count: number;
            /** Total Weekly Records */
            total_weekly_records: number;
            /** Total Revenue */
            total_revenue: number | null;
            /** Avg Weekly Bookings */
            avg_weekly_bookings: number;
            /**
             * Peak Week Date
             * Format: date-time
             */
            peak_week_date: string;
            /** Peak Week Bookings */
            peak_week_bookings: number;
            /** Growth Rate */
            growth_rate: number;
            date_coverage: components["schemas"]["DateCoverage"];
            /** Bookings By Year */
            bookings_by_year: components["schemas"]["BookingsByYear"][];
            /** Bookings By Month */
            bookings_by_month: components["schemas"]["BookingsByMonth"][];
            /**
             * Revenue By Month
             * @default []
             */
            revenue_by_month: components["schemas"]["RevenueByMonth"][];
            holiday_breakdown: components["schemas"]["HolidayBreakdown"];
            /** Avg Lead Time Days */
            avg_lead_time_days?: number | null;
            /**
             * Lead Time Distribution
             * @default []
             */
            lead_time_distribution: components["schemas"]["LeadTimeBucket"][];
            /**
             * Top Airlines
             * @default []
             */
            top_airlines: components["schemas"]["AirlineCount"][];
            /**
             * Top Routes
             * @default []
             */
            top_routes: components["schemas"]["RouteCount"][];
            /**
             * Revenue By Year
             * @default []
             */
            revenue_by_year: components["schemas"]["RevenueByYear"][];
            data_quality?: components["schemas"]["DataQualityReport"] | null;
            /**
             * Available Years
             * @default []
             */
            available_years: string[];
        };
        /** ChartPoint */
        ChartPoint: {
            /** Month */
            month: string;
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
            /** Lowerci */
            lowerCI: number;
            /** Upperci */
            upperCI: number;
        };
        /** CorrelationHeatmapPoint */
        CorrelationHeatmapPoint: {
            /** Variable */
            variable: string;
            /** Correlation */
            correlation: number;
        };
        /** CorrelationPoint */
        CorrelationPoint: {
            /** Lag */
            lag: number;
            /** Value */
            value: number;
        };
        /** CreateInvitationRequest */
        CreateInvitationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "ADMIN" | "ANALYST" | "VIEWER";
        };
        /**
         * CreateInvitationResponse
         * @description The plaintext invite_token is returned EXACTLY ONCE — in this response.
         *     The frontend's responsibility is to display invite_url to the admin
         *     so they can copy/paste it. After this response, the plaintext is
         *     gone forever from our side; only its SHA-256 hash exists in the DB.
         */
        CreateInvitationResponse: {
            /**
             * Invite Id
             * Format: uuid
             */
            invite_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "ADMIN" | "ANALYST" | "VIEWER";
            /** Invite Url */
            invite_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** CriticalForecastWeek */
        CriticalForecastWeek: {
            /**
             * Week Start
             * Format: date-time
             */
            week_start: string;
            /** Week End */
            week_end?: string | null;
            /** Forecasted Volume */
            forecasted_volume: number;
            /** Risk Factor */
            risk_factor: string;
            /** Confidence Tier */
            confidence_tier?: string | null;
        };
        /** DashboardStatsResponse */
        DashboardStatsResponse: {
            /** Total Records */
            total_records: number;
            /** Data Quality Pct */
            data_quality_pct: number;
            /** Revenue Total */
            revenue_total: number;
            /** Growth Rate */
            growth_rate: number;
            /** Expected Bookings */
            expected_bookings: number;
            /** Peak Travel Period */
            peak_travel_period: string;
            /**
             * Bookings Forecast
             * @description Filler
             */
            bookings_forecast?: components["schemas"]["ChartPoint"][];
            /**
             * Yearly Bookings
             * @default []
             */
            yearly_bookings: components["schemas"]["YearlyBookingPoint"][];
        };
        /** DataQualityReport */
        DataQualityReport: {
            /** Total Rows */
            total_rows: number;
            /** Duplicate Rows */
            duplicate_rows: number;
            /** Missing Airline */
            missing_airline: number;
            /** Missing Route */
            missing_route: number;
            /** Missing Travel Date */
            missing_travel_date: number;
            /** Invalid Travel Date */
            invalid_travel_date: number;
            /** Missing Revenue */
            missing_revenue: number;
            /** Quality Score Pct */
            quality_score_pct: number;
        };
        /** DatabaseHealthResponse */
        DatabaseHealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Database */
            database: string;
        };
        /** DateCoverage */
        DateCoverage: {
            /**
             * Start Date
             * Format: date-time
             */
            start_date: string;
            /**
             * End Date
             * Format: date-time
             */
            end_date: string;
            /** Span Weeks */
            span_weeks: number;
        };
        /** ForecastGraphPoint */
        ForecastGraphPoint: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Actual */
            actual?: number | null;
            /** Predicted */
            predicted?: number | null;
            /** Lower Bound */
            lower_bound?: number | null;
            /** Upper Bound */
            upper_bound?: number | null;
            /** Confidence Tier */
            confidence_tier?: string | null;
        };
        /** ForecastGraphResponse */
        ForecastGraphResponse: {
            /** Data */
            data: components["schemas"]["ForecastGraphPoint"][];
        };
        /**
         * ForecastOutlookResponse
         * @description Single endpoint for all Tab 2 KPI cards + critical weeks table.
         *     ISO 25010 Performance Efficiency → Time Behavior:
         *       One query on forecast_cache (indexed on model_id) feeds everything.
         */
        ForecastOutlookResponse: {
            /** Forecasted Bookings 2W */
            forecasted_bookings_2w: number;
            /**
             * Highest Forecast Week Date
             * Format: date-time
             */
            highest_forecast_week_date: string;
            /** Highest Forecast Week Value */
            highest_forecast_week_value: number;
            /** Forecasted Bookings 10W */
            forecasted_bookings_10w: number;
            /** Critical Weeks */
            critical_weeks: components["schemas"]["CriticalForecastWeek"][];
        };
        /** GlobalSettingItem */
        GlobalSettingItem: {
            /** Key */
            key: string;
            /** Value */
            value: unknown;
            /** Description */
            description?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By User Id */
            updated_by_user_id?: string | null;
        };
        /** GlobalSettingsListResponse */
        GlobalSettingsListResponse: {
            /** Items */
            items: components["schemas"]["GlobalSettingItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** HistoricalDataPoint */
        HistoricalDataPoint: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Bookings */
            bookings: number;
            /** Is Holiday */
            is_holiday: boolean;
            /** Weather Indicator */
            weather_indicator?: number | null;
        };
        /** HistoricalDataResponse */
        HistoricalDataResponse: {
            /** Data */
            data: components["schemas"]["HistoricalDataPoint"][];
        };
        /** HolidayBreakdown */
        HolidayBreakdown: {
            /** Holiday Weeks */
            holiday_weeks: number;
            /** Non Holiday Weeks */
            non_holiday_weeks: number;
            /** Holiday Pct */
            holiday_pct: number;
        };
        /** InvitationListItem */
        InvitationListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Intended Role
             * @enum {string}
             */
            intended_role: "ADMIN" | "ANALYST" | "VIEWER";
            /**
             * Created By User Id
             * Format: uuid
             */
            created_by_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Consumed At */
            consumed_at?: string | null;
            /** Consumed By User Id */
            consumed_by_user_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "consumed" | "expired" | "revoked";
        };
        /** InvitationListResponse */
        InvitationListResponse: {
            /** Items */
            items: components["schemas"]["InvitationListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** LeadTimeBucket */
        LeadTimeBucket: {
            /** Bucket */
            bucket: string;
            /** Count */
            count: number;
        };
        /**
         * LoginRequest
         * @description Plaintext credentials. Travels over TLS; never logged; never persisted.
         *     Field-level constraints are deliberately permissive — we let the
         *     auth_service make the actual reject/accept decision based on hash
         *     verification, so that an invalid email shape and a wrong password
         *     return the same opaque 401 (no enumeration).
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description What the frontend gets after a successful login.
         *
         *     `access_expires_at` is included so the frontend can schedule a silent
         *     refresh slightly BEFORE the token actually expires — preventing the UX
         *     failure mode where a user clicks "Save" and gets a 401 mid-flight.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Access Expires At
             * Format: date-time
             */
            access_expires_at: string;
            /**
             * Refresh Expires At
             * Format: date-time
             */
            refresh_expires_at: string;
            user: components["schemas"]["AuthenticatedUser"];
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * MeResponse
         * @description Returned by GET /auth/me. Frontend calls this on app boot to hydrate
         *     the auth context. No tokens here — the frontend already has them.
         */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "ADMIN" | "ANALYST" | "VIEWER";
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelDropdownItem */
        ModelDropdownItem: {
            /** Id */
            id: number;
            /** Model Name */
            model_name: string;
            /** Version */
            version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Aic Score */
            aic_score?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** ModelDropdownResponse */
        ModelDropdownResponse: {
            /** Available Models */
            available_models: components["schemas"]["ModelDropdownItem"][];
        };
        /** ModelParams */
        ModelParams: {
            /** Order */
            order: number[];
            /** Seasonal Order */
            seasonal_order: number[];
            /** Exogenous Features */
            exogenous_features: string[];
        };
        /** ModelRenameRequest */
        ModelRenameRequest: {
            /** New Model Name */
            new_model_name: string;
        };
        /** ModelStatistics */
        ModelStatistics: {
            /** Rmse */
            rmse: number;
            /** Mae */
            mae: number;
            /** Wmape */
            wmape: number;
        };
        /** ModelTests */
        ModelTests: {
            /** Adf Stat */
            adf_stat: number;
            /** Adf Pvalue */
            adf_pvalue: number;
            /** Adf Conclusion */
            adf_conclusion: string;
            /** Ljungbox Stat */
            ljungbox_stat: number;
            /** Ljungbox Pvalue */
            ljungbox_pvalue: number;
            /** Ljungbox Conclusion */
            ljungbox_conclusion: string;
            /** Jarquebera Stat */
            jarquebera_stat: number;
            /** Jarquebera Pvalue */
            jarquebera_pvalue: number;
            /** Jarquebera Conclusion */
            jarquebera_conclusion: string;
        };
        /**
         * PipelineStatusResponse
         * @description Lightweight subset for non-admin Analyst polling (Phase 5 will allow Analyst access).
         */
        PipelineStatusResponse: {
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Model Id */
            last_model_id?: number | null;
            /**
             * Last Status
             * @enum {string}
             */
            last_status: "SUCCESS" | "FAILED" | "NEVER_RUN";
        };
        /** RecentActivityItem */
        RecentActivityItem: {
            /** Id */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Actor Email */
            actor_email?: string | null;
            /** Action Type */
            action_type: string;
            /** Module */
            module: string;
            /**
             * Status
             * @enum {string}
             */
            status: "SUCCESS" | "FAILED";
            /** Target Resource */
            target_resource?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RefreshResponse
         * @description Refresh response is shaped IDENTICALLY to LoginResponse minus `user`.
         *     Reason: the user identity hasn't changed, so the frontend doesn't need
         *     it again. Sending it would invite the frontend to *trust* this payload
         *     over a fresh /auth/me call — and we want the frontend to treat the JWT
         *     as the only source of identity truth.
         */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Access Expires At
             * Format: date-time
             */
            access_expires_at: string;
            /**
             * Refresh Expires At
             * Format: date-time
             */
            refresh_expires_at: string;
        };
        /**
         * RegisterRequest
         * @description Submitted when an invitee clicks the invite URL and sets their password.
         *     The invite_token is the PLAINTEXT half of the (raw, hash) pair generated
         *     by Phase 0's core.security.generate_invite_token; the server SHA-256s it
         *     on arrival to find the matching invite_tokens row.
         */
        RegisterRequest: {
            /** Invite Token */
            invite_token: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /** ResidualPoint */
        ResidualPoint: {
            /** Fitted */
            fitted: number;
            /** Residual */
            residual: number;
        };
        /** RetrainRequest */
        RetrainRequest: {
            /**
             * Time Period
             * @default 30 Days
             * @enum {string}
             */
            time_period: "7 Days" | "14 Days" | "21 Days" | "30 Days" | "90 Days" | "Whole Data Set (2013-Present)";
            /**
             * Target Variable
             * @default Booking Date
             * @constant
             */
            target_variable: "Booking Date";
            /**
             * External Factors
             * @default [
             *       "Typhoon",
             *       "Rainfall Index",
             *       "Temperature",
             *       "Wind Speed",
             *       "Holiday"
             *     ]
             */
            external_factors: string[];
            /**
             * Model Selection
             * @default SARIMAX
             * @enum {string}
             */
            model_selection: "ARIMA" | "SARIMA" | "SARIMAX";
        };
        /** RetrainStatusResponse */
        RetrainStatusResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** New Records Used */
            new_records_used?: number | null;
        };
        /**
         * RevenueByMonth
         * @description Monthly revenue aggregate.
         *     Parallel structure to BookingsByMonth — same month key format ("YYYY-MM")
         *     so the frontend can zip both arrays on the same x-axis without any
         *     client-side date parsing.
         *
         *     ISO 25010 — Maintainability → Reusability:
         *         Defined as a standalone class so future endpoints (e.g. revenue
         *         forecasting) can reference this schema without duplication.
         */
        RevenueByMonth: {
            /** Month */
            month: string;
            /** Revenue */
            revenue: number;
        };
        /** RevenueByYear */
        RevenueByYear: {
            /** Year */
            year: string;
            /** Revenue */
            revenue: number;
        };
        /** RouteCount */
        RouteCount: {
            /** Route */
            route: string;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /** StrategicAction */
        StrategicAction: {
            /** Priority */
            priority: string;
            /** Category */
            category: string;
            /** Action */
            action: string;
            /** Trigger */
            trigger: string;
        };
        /** StrategicActionsResponse */
        StrategicActionsResponse: {
            /** Actions */
            actions: components["schemas"]["StrategicAction"][];
            /** Generated For Period */
            generated_for_period: string;
        };
        /** SystemOverviewResponse */
        SystemOverviewResponse: {
            /** Active Users Count */
            active_users_count: number;
            /** Total Users Count */
            total_users_count: number;
            /** Pending Invitations Count */
            pending_invitations_count: number;
            /** Last Data Sync */
            last_data_sync?: string | null;
            /** Last Data Sync Records */
            last_data_sync_records?: number | null;
            /** Last Forecast Run At */
            last_forecast_run_at?: string | null;
            /** Last Forecast Model Id */
            last_forecast_model_id?: number | null;
            /**
             * Pipeline Status
             * @enum {string}
             */
            pipeline_status: "healthy" | "stale" | "unknown";
            /** Recent Activity */
            recent_activity: components["schemas"]["RecentActivityItem"][];
        };
        /**
         * UpdateSettingRequest
         * @description Generic envelope. Per-key validation is in services/settings_service.py
         *     (Phase 4) — it validates the value's shape AGAINST THE KEY before write.
         *
         *     Why a generic schema and not one model per key:
         *       A handful of typed schemas (one per key) would multiply by N every
         *       time we add a setting. Per-key validation in the service layer
         *       keeps the API surface small while still rejecting bad values at
         *       write time. The validator dispatch is one dict lookup.
         */
        UpdateSettingRequest: {
            /** Value */
            value: unknown;
        };
        /**
         * UpdateUserRequest
         * @description PATCH body. All fields optional; only provided fields are mutated.
         */
        UpdateUserRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Role */
            role?: ("ADMIN" | "ANALYST" | "VIEWER") | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** New Records */
            new_records: number;
        };
        /**
         * UserStatusResponse
         * @description Returned by activate / deactivate. Echoes the resulting state.
         */
        UserStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationPoint */
        ValidationPoint: {
            /** Date Label */
            date_label: string;
            /** Actual */
            actual: number;
            /** Forecasted */
            forecasted: number;
            /** Lower Ci */
            lower_ci: number;
            /** Upper Ci */
            upper_ci: number;
        };
        /** YearlyBookingPoint */
        YearlyBookingPoint: {
            /** Year */
            year: string;
            /** Bookings */
            bookings: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                role?: string | null;
                status?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_user_admin_users__user_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_admin_users__user_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invitations_admin_invitations_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_admin_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_admin_invitations__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_vocabularies_admin_audit_logs_action_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditActionTypesResponse"];
                };
            };
        };
    };
    list_audit_logs_admin_audit_logs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                from_date?: string | null;
                to_date?: string | null;
                action_type?: string | null;
                module?: string | null;
                status?: string | null;
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_log_admin_audit_logs__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_overview_admin_system_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOverviewResponse"];
                };
            };
        };
    };
    pipeline_status_admin_system_pipeline_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStatusResponse"];
                };
            };
        };
    };
    list_settings_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettingsListResponse"];
                };
            };
        };
    };
    get_setting_admin_settings__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_setting_admin_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSettingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthcheck_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    database_healthcheck_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseHealthResponse"];
                };
            };
        };
    };
    get_model_registry_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDropdownResponse"];
                };
            };
        };
    };
    get_dashboard_stats_api_dashboard_stats__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_business_analytics_api_business_analytics_get: {
        parameters: {
            query?: {
                model_id?: number | null;
                year?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_advanced_metrics_api_advanced_metrics__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvancedMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_outlook_api_forecast_outlook__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastOutlookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_historical_ledger_api_historical_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalDataResponse"];
                };
            };
        };
    };
    upload_pos_data_api_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_pos_data_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_graph_api_forecast_graph__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategic_actions_api_strategic_actions__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategicActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_retrain_api_retrain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrainStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_model_api_models__model_id__rename_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
